NUMPY - NUMERICAL PYTHON
ALLOW FASTEST NUMERICAL VARIOUS OPERATIONS

In [1]:
import numpy as np

In [7]:
from time import process_time 
python_list = [i for i in range(10)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

3.0999999999892225e-05


In [11]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr) #DEFINE ARRAY
arr.shape #TO GET NUMBER OF COLUMNS AND ROWS

[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
y = np.eye(3)
print(y) #IDENTITY MATRIX

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
X = np.zeros((5,5))
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#CONVERT LIST INTO NUMPY ARRAY

list = [1,2,3,4,5]
print(list)
a = np.asanyarray(list)
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [17]:
#DIAMENSION
print(a.ndim)

1


In [19]:
#SIZE
print(a.size)

5
